# Generated by Django 4.0.5 on 2022-06-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_of_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('full_text', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='media/')),
                ('author', models.CharField(max_length=50)),
                ('author_img', models.ImageField(default='1.png', upload_to='media/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.group_of_news')),
            ],
        ),
    ]
