# Generated by Django 4.0.5 on 2022-06-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author_img',
            field=models.ImageField(default='1.jpg', upload_to='media/'),
        ),
    ]
