# Generated by Django 4.0.5 on 2022-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author_img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
