# Generated by Django 4.0.5 on 2022-06-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesforus',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('worked', 'worked')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagesforus',
            name='user_message',
            field=models.TextField(verbose_name='message'),
        ),
    ]
