# Generated by Django 4.0.5 on 2022-07-04 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_messagesforus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesforus',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 17, 43, 0, 469510), verbose_name='data'),
        ),
    ]
