# Generated by Django 4.0.5 on 2022-07-06 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_messagesforus_options_alter_messagesforus_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesforus',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 10, 53, 23, 558275), verbose_name='data'),
        ),
    ]
